<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Build Results - Go</string>

    <key>scopeName</key>
    <string>source.build-results-go</string>

    <key>author</key>
    <string>https://github.com/frou</string>

    <key>patterns</key>
    <array>

        <dict>
            <key>name</key>
            <string>comment.sublime-inband.build-results-go</string>

            <key>match</key>
            <string>^\[.+\]$</string>
        </dict>

<!--
        <dict>
            <key>name</key>
            <string>comment.mundane-suggestions.golint.build-results-go</string>

            <key>match</key>
            <string>(?x)
            ^
            .+?:
            \s+
            (
                exported\s\w+\s[\w\.]+\sshould\shave\scomment\s(\(or\sa\scomment\son\sthis\sblock\)\s)?or\sbe\sunexported
                |
                (const|var|func(\s(parameter|result))?|method|type)\s\w+\sshould\sbe\s\w+
            )
            \s+
            \(golint\)
            $
            </string>
        </dict>

        <dict>
            <key>name</key>
            <string>comment.mundane-suggestions.gas.build-results-go</string>

            <key>match</key>
            <string>(?x)
            ^
            .+?:
            \s+
            (
                Errors\sunhandled\..*
            )
            \s+
            \(gas\)
            $
            </string>
        </dict>

        <dict>
            <key>name</key>
            <string>comment.mundane-suggestions.errcheck.build-results-go</string>

            <key>match</key>
            <string>(?x)
            ^
            .+?:
            \s+
            (
                Error\sreturn\svalue\sof\s`\w+\.(Close)`\sis\snot\schecked
            )
            \s+
            \(errcheck\)
            $
            </string>
        </dict>
-->

        <dict>
            <key>name</key>
            <string>entity.package.build-results-go</string>

            <key>match</key>
            <string>^# .+</string>
        </dict>

        <dict>
            <key>name</key>
            <string>constant.location.build-results-go</string>

            <key>match</key>
            <string>^\s*(.+?):([0-9]+)(?::([0-9]+))?:?</string>
        </dict>

        <dict>
            <key>name</key>
            <string>storage.type.linter.build-results-go</string>

            <key>match</key>
            <string>(?&lt;=  )\w+(?=  )</string>
        </dict>

    </array>
</dict>
</plist>
