<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Build Results - Go</string>

    <key>scopeName</key>
    <string>source.build-results-go</string>

    <key>author</key>
    <string>https://github.com/frou</string>

    <key>patterns</key>
    <array>

        <dict>
            <key>name</key>
            <string>comment.sublime-inband.build-results-go</string>

            <key>match</key>
            <string>^\[.+\]$</string>
        </dict>

        <dict>
            <key>name</key>
            <string>comment.golint-mundane-suggestions.build-results-go</string>

            <key>match</key>
            <string>(?x)
            ^
            .+?:\s+
            golint\s+
            \w+\s+
            (
                exported\s\w+\s[\w\.]+\sshould\shave\scomment\s(\(or\sa\scomment\son\sthis\sblock\)\s)?or\sbe\sunexported
                |
                (const|var|func(\s(parameter|result))?|type)\s\w+\sshould\sbe\s\w+
            )
            $
        </string>
        </dict>

        <dict>
            <key>name</key>
            <string>entity.package.build-results-go</string>

            <key>match</key>
            <string>^# .+</string>
        </dict>

        <dict>
            <key>name</key>
            <string>constant.location.build-results-go</string>

            <key>match</key>
            <string>^\s*(.+?):([0-9]+):([0-9]+)?:?</string>
        </dict>

    </array>
</dict>
</plist>
