<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Build Results - Go</string>

    <key>scopeName</key>
    <string>source.build-results-go</string>

    <key>author</key>
    <string>https://github.com/frou</string>

    <key>patterns</key>
    <array>

        <dict>
            <key>name</key>
            <string>comment.sublime-inband.build-results-go</string>

            <key>match</key>
            <string>^\[.+\]$</string>
        </dict>

        <dict>
            <key>name</key>
            <string>comment.golint-mundane-suggestions.build-results-go</string>

            <key>match</key>
            <string>\b(exported \w+ [\w\.]+ should have comment (\(or a comment on this block\) )?or be unexported)\b</string>
        </dict>

        <dict>
            <key>name</key>
            <string>entity.package.build-results-go</string>

            <key>match</key>
            <string>^# .+</string>
        </dict>

        <dict>
            <key>name</key>
            <string>constant.location.build-results-go</string>

            <key>match</key>
            <string>^\s*(.+?):([0-9]+):([0-9]+)?:?</string>
        </dict>

        <!-- gometalinter results -->

        <dict>
            <key>name</key>
            <string>keyword.linter.build-results-go</string>

            <key>match</key>
            <string>\s\([\w\-]+\)$</string>
        </dict>

        <dict>
            <key>name</key>
            <string>storage.type.severity.build-results-go</string>

            <key>match</key>
            <string>(?&lt;=:)(warning|error):\s</string>
        </dict>

    </array>
</dict>
</plist>
